// ObjIO.cpp
// 实现 OBJ 模型文件的读取、三角化和保存。

#include "mesh/ObjIO.h"

#include <fstream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace mesh {
namespace {

// 生成带文件路径和行号的错误信息。
std::string makeLineError(const std::filesystem::path& path, std::size_t line_number, const std::string& message) {
    std::ostringstream out;
    out << path.string() << ":" << line_number << ": " << message;
    return out.str();
}

// 解析 OBJ 面元素中的顶点下标。
std::size_t parseObjVertexIndex(
    const std::string& token,
    std::size_t vertex_count,
    const std::filesystem::path& path,
    std::size_t line_number
) {
    const std::size_t slash_pos = token.find('/');
    const std::string index_text = token.substr(0, slash_pos);
    if (index_text.empty()) {
        throw std::runtime_error(makeLineError(path, line_number, "face vertex index is empty"));
    }

    int obj_index = 0;
    try {
        obj_index = std::stoi(index_text);
    } catch (const std::exception&) {
        throw std::runtime_error(makeLineError(path, line_number, "face vertex index is not an integer: " + token));
    }

    if (obj_index == 0) {
        throw std::runtime_error(makeLineError(path, line_number, "OBJ indices start at 1, not 0"));
    }

    const int resolved = obj_index > 0 ? obj_index - 1 : static_cast<int>(vertex_count) + obj_index;
    if (resolved < 0 || static_cast<std::size_t>(resolved) >= vertex_count) {
        throw std::runtime_error(makeLineError(path, line_number, "face vertex index is out of range: " + token));
    }

    return static_cast<std::size_t>(resolved);
}

}  // namespace

// 从 OBJ 文件读取网格，只保留顶点坐标和三角面索引。
Mesh loadObj(const std::filesystem::path& path) {
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("failed to open OBJ file: " + path.string());
    }

    Mesh mesh;
    // line_number 用于定位 OBJ 文件中的格式错误。
    std::string line;
    std::size_t line_number = 0;

    while (std::getline(input, line)) {
        ++line_number;

        std::istringstream line_stream(line);
        std::string tag;
        line_stream >> tag;

        if (tag.empty() || tag == "#") {
            continue;
        }

        if (tag == "v") {
            Vec3 p;
            if (!(line_stream >> p.x >> p.y >> p.z)) {
                throw std::runtime_error(makeLineError(path, line_number, "invalid vertex position"));
            }
            mesh.positions.push_back(p);
            continue;
        }

        if (tag == "f") {
            // polygon_indices 保存当前面的顶点下标，用于三角化。
            std::vector<std::size_t> polygon_indices;
            std::string token;
            while (line_stream >> token) {
                polygon_indices.push_back(parseObjVertexIndex(token, mesh.positions.size(), path, line_number));
            }

            if (polygon_indices.size() < 3) {
                throw std::runtime_error(makeLineError(path, line_number, "face must contain at least 3 vertices"));
            }

            for (std::size_t i = 1; i + 1 < polygon_indices.size(); ++i) {
                mesh.faces.push_back(Face{{polygon_indices[0], polygon_indices[i], polygon_indices[i + 1]}});
            }
        }
    }

    if (mesh.positions.empty()) {
        throw std::runtime_error("OBJ file contains no vertices: " + path.string());
    }

    return mesh;
}

// 将网格保存为 OBJ 文件。
void saveObj(const Mesh& mesh, const std::filesystem::path& path) {
    std::ofstream output(path);
    if (!output) {
        throw std::runtime_error("failed to write OBJ file: " + path.string());
    }

    output << "# Generated by Mesh LOD Tool\n";
    for (const Vec3& p : mesh.positions) {
        output << "v " << p.x << ' ' << p.y << ' ' << p.z << '\n';
    }

    for (const Face& face : mesh.faces) {
        output << "f "
               << face.vertex_indices[0] + 1 << ' '
               << face.vertex_indices[1] + 1 << ' '
               << face.vertex_indices[2] + 1 << '\n';
    }
}

}  // namespace mesh
